### ISSUE TITLE
Set rethrow to false

### ISSUE THREAD

**Issue by tlienart** [JuliaDocs/IOCapture.jl#12]
https://github.com/JuliaDocs/IOCapture.jl/blob/d8b27045cec8953e0e5a8d719ca1692b3a6d0d02/src/IOCapture.jl#L50-L55

is this correct? should it not be `;rethrow = Union{}` as in the tests? setting `rethrow=false` leads to a TypeError.

**Comment by mortenpi** [comment]
The docstring simply seems to be outdated. We got rid of the `Bool`s in 0.2.0: https://github.com/JuliaDocs/IOCapture.jl/pull/2#issuecomment-716832132
